- name: Setup Python
  uses: actions/setup-python@v4
  with:
  python-version: '3.10
- name: Install Dependencies
  run: pip install -r requirements.txt
- name: pass Inputs to Shell
  run: |
        echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
- name: Fetch the number's square
  run: python src/get_num_squar.py
  
